CREATE TABLE IF NOT EXISTS mst_slotitem (
    api_id INTEGER PRIMARY KEY,
    api_sortno INTEGER,
    api_name TEXT,
    api_type TEXT,
    api_taik INTEGER,
    api_souk INTEGER,
    api_houg INTEGER,
    api_raig INTEGER,
    api_soku INTEGER,
    api_baku INTEGER,
    api_tyku INTEGER,
    api_tais INTEGER,
    api_atap INTEGER,
    api_houm INTEGER,
    api_raim INTEGER,
    api_houk INTEGER,
    api_raik INTEGER,
    api_bakk INTEGER,
    api_saku INTEGER,
    api_sakb INTEGER,
    api_luck INTEGER,
    api_leng INTEGER,
    api_cost INTEGER,
    api_distance INTEGER,
    api_rare INTEGER,
    api_broken TEXT,
    api_usebull TEXT,
    api_version INTEGER
);