CREATE TABLE IF NOT EXISTS ship (
    api_id INTEGER PRIMARY KEY,
    api_backs INTEGER,
    api_bull INTEGER,
    api_cond INTEGER,
    api_exp TEXT,
    api_fuel INTEGER,
    api_kaihi TEXT,
    api_karyoku TEXT,
    api_kyouka TEXT,
    api_leng INTEGER,
    api_locked INTEGER,
    api_locked_equip INTEGER,
    api_lucky TEXT,
    api_lv INTEGER,
    api_maxhp INTEGER,
    api_ndock_item TEXT,
    api_ndock_time INTEGER,
    api_nowhp INTEGER,
    api_onslot TEXT,
    api_raisou TEXT,
    api_sakuteki TEXT,
    api_ship_id INTEGER,
    api_slot TEXT,
    api_slot_ex INTEGER,
    api_slotnum INTEGER,
    api_soku INTEGER,
    api_sortno INTEGER,
    api_soukou TEXT,
    api_srate INTEGER,
    api_taiku TEXT,
    api_taisen TEXT
);